language: node_js
node_js: 
- "6.9.2"
branches:
  only:
    - develop
install:
- npm install
script:
  - npm run test
services: 
  - postgresql
cache: 
  directories:
  - "node_modules"
before_script:
  - psql -c 'CREATE DATABASE travis;' -U postgres

