language: node_js
node_js: 
- "6.9.2"
branches:
  only:
    - develop
install:
- npm install
script:
  - npm test
services: 
  - postgresql
cache: 
  directories:
  - "node_modules"
env:
- NODE_ENV=test

before_script:
  - npm install sequelize -g
  - npm install nyc -g
  - npm install mocha -g
  - psql -c 'create database More-Recipes-tests;' -U postgres
