language: node_js
node_js: 
- "6.9.2"
branches:
  only:
    - develop
install:
- npm install
script:
  - npm test
services: 
  - postgresql
cache: 
  directories:
  - "node_modules"
env:
- NODE_ENV=test

before_script:
  - npm install nyc -g
  - npm install mocha -g
  - createdb More-Recipes-tests --username=postgres
  - sequelize db:migrate

services:
 - postgresql